apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    version: "1"
  name: apache-8080
spec:
  containers:
  - image: bitnami/apache
    name: apache-8080
    ports:
    - containerPort: 8080
      name: "8080-port"
    env:
      - name: APACHE_HTTP_PORT_NUMBER
        value: "8080"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
