apiVersion: v1
kind: Service
metadata:
  name: external-lb
spec:
  type: LoadBalancer
  ports:
  - name: apache
    port: 8080
    targetPort: "8080-port"
  - name: nginx
    port: 80
    targetPort: "80-port"
  selector:
    app: nginx
  #allocateLoadBalancerNodePorts: false
