apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: nginx
    version: "1"
  name: nginx-80
spec:
  containers:
  - image: nginx
    name: nginx-80
    ports:
    - containerPort: 80
      name: "80-port"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
